// Code generated by goroot-overlay/aesgcm_riscv64_gen.py. DO NOT EDIT.

// NanoKVM (ironkvm-dist#72, run sheet trial 66): see the generator and
// goroot-overlay/overlay.sh.

//go:build !purego

#include "textflag.h"

// func ghashBlocksAsm(t *ghashTable8, y *gcmFieldElement, data *byte, n int)
//
// For n >= 1 blocks of 16 bytes: y = (y + block) * H, per block.
TEXT ·ghashBlocksAsm(SB), NOSPLIT, $0-32
	MOV	t+0(FP), X10
	ADD	$2048, X10, X11
	MOV	$·ghashReduce8(SB), X12
	MOV	y+8(FP), X13
	MOV	data+16(FP), X14
	MOV	n+24(FP), X15
	MOV	0(X13), X16
	MOV	8(X13), X17
ghash_block:
	MOV	0(X14), X23
	MOV	8(X14), X24
	WORD	$0x820b9b8b	// th.rev X23, X23
	WORD	$0x820c1c0b	// th.rev X24, X24
	XOR	X23, X16, X16
	XOR	X24, X17, X17
	WORD	$0x1c08ba0b	// th.extu X20, X17, 7, 0
	WORD	$0x6745490b	// th.lrd X18, X10, X20, 3
	WORD	$0x6745c98b	// th.lrd X19, X11, X20, 3
	WORD	$0x3c88ba0b	// th.extu X20, X17, 15, 8
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x5d08ba0b	// th.extu X20, X17, 23, 16
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x7d88ba0b	// th.extu X20, X17, 31, 24
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x9e08ba0b	// th.extu X20, X17, 39, 32
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xbe88ba0b	// th.extu X20, X17, 47, 40
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xdf08ba0b	// th.extu X20, X17, 55, 48
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xff88ba0b	// th.extu X20, X17, 63, 56
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x1c083a0b	// th.extu X20, X16, 7, 0
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x3c883a0b	// th.extu X20, X16, 15, 8
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x5d083a0b	// th.extu X20, X16, 23, 16
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x7d883a0b	// th.extu X20, X16, 31, 24
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0x9e083a0b	// th.extu X20, X16, 39, 32
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xbe883a0b	// th.extu X20, X16, 47, 40
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xdf083a0b	// th.extu X20, X16, 55, 48
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	WORD	$0xff883a0b	// th.extu X20, X16, 63, 56
	AND	$0xff, X19, X21
	WORD	$0x67454b8b	// th.lrd X23, X10, X20, 3
	WORD	$0x6745cc0b	// th.lrd X24, X11, X20, 3
	WORD	$0x67564c8b	// th.lrd X25, X12, X21, 3
	SRL	$8, X19, X19
	SLL	$56, X18, X22
	SRL	$8, X18, X18
	OR	X22, X19, X19
	XOR	X23, X18, X18
	XOR	X24, X19, X19
	XOR	X25, X18, X18
	MOV	X18, X16
	MOV	X19, X17
	ADD	$16, X14, X14
	SUB	$1, X15, X15
	BNE	X15, ZERO, ghash_block
	MOV	X16, 0(X13)
	MOV	X17, 8(X13)
	RET
