#!/usr/bin/env python3
# Generates the riscv64 AES and GHASH assembly of the goroot overlay:
#
#   src/crypto/internal/fips140/aes/aes_riscv64.s
#   src/crypto/internal/fips140/aes/gcm/gcm_riscv64.s
#
#   python3 aesgcm_riscv64_gen.py     (from server/goroot-overlay)
#
# See overlay.sh for why these exist (ironkvm-dist#72, run sheet trial 66).
#
# Both use two T-Head extensions the C906 implements and that both of the
# board's kernels leave enabled (mxstatus.THEADISAEE; the server's own C code
# is built with -march=...xthead and uses them too): XTheadBb th.extu (bit
# field extract) and th.revw / th.rev (byte reverse), and XTheadMemIdx
# th.lrbu / th.lrwu / th.lrd (load from base + index << shift). The Go
# assembler has no mnemonics for them, so they are emitted as WORDs with the
# mnemonic in a comment. tools/bench/t66/theadprobe in ironkvm-dist checks
# them on a device.
#
# AES: the T-table method of the toolchain's encryptBlockGeneric (aes_generic.go,
# the te0..te3 and sbox0 tables of const.go), one round of a column being four
# th.extu, four th.lrwu and four XORs. Variable time, like the generic code
# it replaces.
#
# GHASH: Shoup's method with 8-bit tables. Per key, gcm_riscv64.go fills
# 256 multiples of H (lo and hi words apart, 4 KB); a static table holds the
# reduction of the 8 bits shifted out per step. Field elements are the
# generic code's gcmFieldElement (ghash.go): big-endian words, the
# coefficient of x^0 in the top bit of low. Variable time, like ghash.go.
import os


def xr(r):
    return int(r.lstrip("X"))


def word(v, text):
    return "\tWORD\t$0x%08x\t// %s" % (v, text)


def th_extu(rd, rs1, msb, lsb):
    v = (msb << 26) | (lsb << 20) | (xr(rs1) << 15) | (0b011 << 12) | (xr(rd) << 7) | 0x0B
    return word(v, "th.extu %s, %s, %d, %d" % (rd, rs1, msb, lsb))


def _ldx(f5, name):
    def f(rd, rs1, rs2, sh):
        v = (f5 << 27) | (sh << 25) | (xr(rs2) << 20) | (xr(rs1) << 15) | (0b100 << 12) | (xr(rd) << 7) | 0x0B
        return word(v, "%s %s, %s, %s, %d" % (name, rd, rs1, rs2, sh))
    return f


th_lrbu = _ldx(0b10000, "th.lrbu")
th_lrwu = _ldx(0b11000, "th.lrwu")
th_lrd = _ldx(0b01100, "th.lrd")


def _un(f7, name):
    def f(rd, rs1):
        v = (f7 << 25) | (xr(rs1) << 15) | (0b001 << 12) | (xr(rd) << 7) | 0x0B
        return word(v, "%s %s, %s" % (name, rd, rs1))
    return f


th_rev = _un(0b1000001, "th.rev")
th_revw = _un(0b1001000, "th.revw")


def byte_of(rd, rs, shift):
    """rd = (rs >> shift) & 0xff."""
    return th_extu(rd, rs, shift + 7, shift)


HEADER = """// Code generated by goroot-overlay/aesgcm_riscv64_gen.py. DO NOT EDIT.

// NanoKVM (ironkvm-dist#72, run sheet trial 66): see the generator and
// goroot-overlay/overlay.sh.

//go:build !purego

#include "textflag.h"
"""

# ---------------------------------------------------------------- AES

XK, END = "X10", "X11"            # round keys; address of the last round key
TE = ["X12", "X13", "X14", "X15"]  # te0..te3
SBOX = "X16"
S = ["X17", "X18", "X19", "X20"]
T = ["X21", "X22", "X23", "X24"]
TMP = ["X25", "X26", "X28", "X29"]
KP = "X30"                        # round key pointer


def aes_tables():
    out = []
    for i, r in enumerate(TE):
        out.append("\tMOV\t$·te%d(SB), %s" % (i, r))
    out.append("\tMOV\t$·sbox0(SB), %s" % SBOX)
    return out


def aes_round(src, dst, koff):
    """dst = one middle round of src with the round key at koff(KP)."""
    out = []
    for j in range(4):
        out.append("\tMOVWU\t%d(%s), %s" % (koff + 4 * j, KP, dst[j]))
    for j in range(4):
        # t_j = rk ^ te0[s_j>>24] ^ te1[s_j+1>>16] ^ te2[s_j+2>>8] ^ te3[s_j+3]
        srcs = [(src[j], 24), (src[(j + 1) % 4], 16), (src[(j + 2) % 4], 8), (src[(j + 3) % 4], 0)]
        for t, (s, sh) in zip(TMP, srcs):
            out.append(byte_of(t, s, sh))
        for k, t in enumerate(TMP):
            out.append(th_lrwu(t, TE[k], t, 2))
        for t in TMP:
            out.append("\tXOR\t%s, %s, %s" % (t, dst[j], dst[j]))
    return out


def aes_last(src, dst):
    """dst = the last round of src (big-endian words), key at 0(END)."""
    out = []
    for j in range(4):
        out.append("\tMOVWU\t%d(%s), %s" % (4 * j, END, dst[j]))
    for j in range(4):
        srcs = [(src[j], 24), (src[(j + 1) % 4], 16), (src[(j + 2) % 4], 8), (src[(j + 3) % 4], 0)]
        for t, (s, sh) in zip(TMP, srcs):
            out.append(byte_of(t, s, sh))
        for t in TMP:
            out.append(th_lrbu(t, SBOX, t, 0))
        for t, (_, sh) in zip(TMP, srcs):
            if sh:
                out.append("\tSLL\t$%d, %s, %s" % (sh, t, t))
        for t in TMP:
            out.append("\tXOR\t%s, %s, %s" % (t, dst[j], dst[j]))
    return out


def aes_core(label):
    """S (big-endian words, key 0 already added) -> S encrypted. KP = XK on entry."""
    out = []
    out.append("\tADD\t$16, %s, %s" % (XK, KP))
    out.append("%s:" % label)
    out += aes_round(S, T, 0)
    out += aes_round(T, S, 16)
    out.append("\tADD\t$32, %s, %s" % (KP, KP))
    out.append("\tADD\t$16, %s, %s" % (KP, TMP[0]))
    out.append("\tBNE\t%s, %s, %s" % (TMP[0], END, label))
    out += aes_round(S, T, 0)
    out += aes_last(T, S)
    return out


def aes_end_pointer():
    # END = XK + 16*nr, the last round key.
    return ["\tSLL\t$4, %s, %s" % (END, END), "\tADD\t%s, %s, %s" % (XK, END, END)]


def gen_aes():
    out = [HEADER]
    out.append("""// func encryptBlockAsm(nr int, xk *uint32, dst, src *byte)
TEXT ·encryptBlockAsm(SB), NOSPLIT, $0-32
\tMOV\tnr+0(FP), %s
\tMOV\txk+8(FP), %s
\tMOV\tdst+16(FP), X5
\tMOV\tsrc+24(FP), X6""" % (END, XK))
    out += aes_end_pointer()
    out += aes_tables()
    for j in range(4):
        out.append("\tMOVWU\t%d(X6), %s" % (4 * j, S[j]))
        out.append(th_revw(S[j], S[j]))
        out.append("\tMOVWU\t%d(%s), %s" % (4 * j, XK, T[j]))
        out.append("\tXOR\t%s, %s, %s" % (T[j], S[j], S[j]))
    out += aes_core("enc_rounds")
    for j in range(4):
        out.append(th_revw(S[j], S[j]))
        out.append("\tMOVW\t%s, %d(X5)" % (S[j], 4 * j))
    out.append("\tRET\n")

    # GCM's counter mode: the last four bytes of the counter block are a
    # big-endian counter that wraps at 32 bits.
    out.append("""// func ctr32BlocksAsm(nr int, xk *uint32, dst, src *byte, n int, counter *byte)
//
// For n >= 1 blocks: dst = src ^ AES(counter), counter[12:16]++ (big-endian,
// wrapping at 2^32), per block. dst and src may be the same.
TEXT ·ctr32BlocksAsm(SB), NOSPLIT, $0-48
\tMOV\tnr+0(FP), %s
\tMOV\txk+8(FP), %s
\tMOV\tdst+16(FP), X5
\tMOV\tsrc+24(FP), X6
\tMOV\tn+32(FP), X7
\tMOV\tcounter+40(FP), X8""" % (END, XK))
    out += aes_end_pointer()
    out += aes_tables()
    out.append("\tMOVWU\t12(X8), X9")
    out.append(th_revw("X9", "X9"))
    out.append("ctr_block:")
    for j in range(3):
        out.append("\tMOVWU\t%d(X8), %s" % (4 * j, S[j]))
        out.append(th_revw(S[j], S[j]))
    out.append("\tMOV\tX9, %s" % S[3])
    for j in range(4):
        out.append("\tMOVWU\t%d(%s), %s" % (4 * j, XK, T[j]))
        out.append("\tXOR\t%s, %s, %s" % (T[j], S[j], S[j]))
    out += aes_core("ctr_rounds")
    for j in range(4):
        out.append(th_revw(S[j], S[j]))
        out.append("\tMOVWU\t%d(X6), %s" % (4 * j, T[j]))
    for j in range(4):
        out.append("\tXOR\t%s, %s, %s" % (S[j], T[j], T[j]))
        out.append("\tMOVW\t%s, %d(X5)" % (T[j], 4 * j))
    out.append("\tADDW\t$1, X9, X9")
    out.append("\tADD\t$16, X5, X5")
    out.append("\tADD\t$16, X6, X6")
    out.append("\tSUB\t$1, X7, X7")
    out.append("\tBNE\tX7, ZERO, ctr_block")
    out.append(th_revw("X9", "X9"))
    out.append("\tMOVW\tX9, 12(X8)")
    out.append("\tRET\n")
    return "\n".join(out)


# ---------------------------------------------------------------- GHASH

LO, HI, RED = "X10", "X11", "X12"   # b*H low words, high words; reduction
YP, DATA, N = "X13", "X14", "X15"
YL, YH, ZL, ZH = "X16", "X17", "X18", "X19"
B, REM, SH, M1, M2, R = "X20", "X21", "X22", "X23", "X24", "X25"


def ghash_step(src, shift, first):
    """Z = Z*x^8 + byte(src, shift)*H, or Z = byte*H for the first byte."""
    out = [byte_of(B, src, shift)]
    if first:
        out.append(th_lrd(ZL, LO, B, 3))
        out.append(th_lrd(ZH, HI, B, 3))
        return out
    out.append("\tAND\t$0xff, %s, %s" % (ZH, REM))
    out.append(th_lrd(M1, LO, B, 3))
    out.append(th_lrd(M2, HI, B, 3))
    out.append(th_lrd(R, RED, REM, 3))
    out.append("\tSRL\t$8, %s, %s" % (ZH, ZH))
    out.append("\tSLL\t$56, %s, %s" % (ZL, SH))
    out.append("\tSRL\t$8, %s, %s" % (ZL, ZL))
    out.append("\tOR\t%s, %s, %s" % (SH, ZH, ZH))
    out.append("\tXOR\t%s, %s, %s" % (M1, ZL, ZL))
    out.append("\tXOR\t%s, %s, %s" % (M2, ZH, ZH))
    out.append("\tXOR\t%s, %s, %s" % (R, ZL, ZL))
    return out


def gen_gcm():
    out = [HEADER]
    out.append("""// func ghashBlocksAsm(t *ghashTable8, y *gcmFieldElement, data *byte, n int)
//
// For n >= 1 blocks of 16 bytes: y = (y + block) * H, per block.
TEXT ·ghashBlocksAsm(SB), NOSPLIT, $0-32
\tMOV\tt+0(FP), %s
\tADD\t$2048, %s, %s
\tMOV\t$·ghashReduce8(SB), %s
\tMOV\ty+8(FP), %s
\tMOV\tdata+16(FP), %s
\tMOV\tn+24(FP), %s
\tMOV\t0(%s), %s
\tMOV\t8(%s), %s
ghash_block:
\tMOV\t0(%s), %s
\tMOV\t8(%s), %s""" % (LO, LO, HI, RED, YP, DATA, N, YP, YL, YP, YH, DATA, M1, DATA, M2))
    out.append(th_rev(M1, M1))
    out.append(th_rev(M2, M2))
    out.append("\tXOR\t%s, %s, %s" % (M1, YL, YL))
    out.append("\tXOR\t%s, %s, %s" % (M2, YH, YH))
    # Horner's rule from the x^127 end: bytes 15..8 (YH, low byte first),
    # then 7..0 (YL).
    first = True
    for src in (YH, YL):
        for shift in range(0, 64, 8):
            out += ghash_step(src, shift, first)
            first = False
    out.append("\tMOV\t%s, %s" % (ZL, YL))
    out.append("\tMOV\t%s, %s" % (ZH, YH))
    out.append("\tADD\t$16, %s, %s" % (DATA, DATA))
    out.append("\tSUB\t$1, %s, %s" % (N, N))
    out.append("\tBNE\t%s, ZERO, ghash_block" % N)
    out.append("\tMOV\t%s, 0(%s)" % (YL, YP))
    out.append("\tMOV\t%s, 8(%s)" % (YH, YP))
    out.append("\tRET\n")
    return "\n".join(out)


here = os.path.dirname(os.path.abspath(__file__))
base = os.path.join(here, "src", "crypto", "internal", "fips140", "aes")
with open(os.path.join(base, "aes_riscv64.s"), "w", encoding="utf-8", newline="\n") as f:
    f.write(gen_aes())
with open(os.path.join(base, "gcm", "gcm_riscv64.s"), "w", encoding="utf-8", newline="\n") as f:
    f.write(gen_gcm())
