// Code generated by goroot-overlay/aesgcm_riscv64_gen.py. DO NOT EDIT.

// NanoKVM (ironkvm-dist#72, run sheet trial 66): see the generator and
// goroot-overlay/overlay.sh.

//go:build !purego

#include "textflag.h"

// func encryptBlockAsm(nr int, xk *uint32, dst, src *byte)
TEXT ·encryptBlockAsm(SB), NOSPLIT, $0-32
	MOV	nr+0(FP), X11
	MOV	xk+8(FP), X10
	MOV	dst+16(FP), X5
	MOV	src+24(FP), X6
	SLL	$4, X11, X11
	ADD	X10, X11, X11
	MOV	$·te0(SB), X12
	MOV	$·te1(SB), X13
	MOV	$·te2(SB), X14
	MOV	$·te3(SB), X15
	MOV	$·sbox0(SB), X16
	MOVWU	0(X6), X17
	WORD	$0x9008988b	// th.revw X17, X17
	MOVWU	0(X10), X21
	XOR	X21, X17, X17
	MOVWU	4(X6), X18
	WORD	$0x9009190b	// th.revw X18, X18
	MOVWU	4(X10), X22
	XOR	X22, X18, X18
	MOVWU	8(X6), X19
	WORD	$0x9009998b	// th.revw X19, X19
	MOVWU	8(X10), X23
	XOR	X23, X19, X19
	MOVWU	12(X6), X20
	WORD	$0x900a1a0b	// th.revw X20, X20
	MOVWU	12(X10), X24
	XOR	X24, X20, X20
	ADD	$16, X10, X30
enc_rounds:
	MOVWU	0(X30), X21
	MOVWU	4(X30), X22
	MOVWU	8(X30), X23
	MOVWU	12(X30), X24
	WORD	$0x7d88bc8b	// th.extu X25, X17, 31, 24
	WORD	$0x5d093d0b	// th.extu X26, X18, 23, 16
	WORD	$0x3c89be0b	// th.extu X28, X19, 15, 8
	WORD	$0x1c0a3e8b	// th.extu X29, X20, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X21, X21
	XOR	X26, X21, X21
	XOR	X28, X21, X21
	XOR	X29, X21, X21
	WORD	$0x7d893c8b	// th.extu X25, X18, 31, 24
	WORD	$0x5d09bd0b	// th.extu X26, X19, 23, 16
	WORD	$0x3c8a3e0b	// th.extu X28, X20, 15, 8
	WORD	$0x1c08be8b	// th.extu X29, X17, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X22, X22
	XOR	X26, X22, X22
	XOR	X28, X22, X22
	XOR	X29, X22, X22
	WORD	$0x7d89bc8b	// th.extu X25, X19, 31, 24
	WORD	$0x5d0a3d0b	// th.extu X26, X20, 23, 16
	WORD	$0x3c88be0b	// th.extu X28, X17, 15, 8
	WORD	$0x1c093e8b	// th.extu X29, X18, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X23, X23
	XOR	X26, X23, X23
	XOR	X28, X23, X23
	XOR	X29, X23, X23
	WORD	$0x7d8a3c8b	// th.extu X25, X20, 31, 24
	WORD	$0x5d08bd0b	// th.extu X26, X17, 23, 16
	WORD	$0x3c893e0b	// th.extu X28, X18, 15, 8
	WORD	$0x1c09be8b	// th.extu X29, X19, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X24, X24
	XOR	X26, X24, X24
	XOR	X28, X24, X24
	XOR	X29, X24, X24
	MOVWU	16(X30), X17
	MOVWU	20(X30), X18
	MOVWU	24(X30), X19
	MOVWU	28(X30), X20
	WORD	$0x7d8abc8b	// th.extu X25, X21, 31, 24
	WORD	$0x5d0b3d0b	// th.extu X26, X22, 23, 16
	WORD	$0x3c8bbe0b	// th.extu X28, X23, 15, 8
	WORD	$0x1c0c3e8b	// th.extu X29, X24, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X17, X17
	XOR	X26, X17, X17
	XOR	X28, X17, X17
	XOR	X29, X17, X17
	WORD	$0x7d8b3c8b	// th.extu X25, X22, 31, 24
	WORD	$0x5d0bbd0b	// th.extu X26, X23, 23, 16
	WORD	$0x3c8c3e0b	// th.extu X28, X24, 15, 8
	WORD	$0x1c0abe8b	// th.extu X29, X21, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X18, X18
	XOR	X26, X18, X18
	XOR	X28, X18, X18
	XOR	X29, X18, X18
	WORD	$0x7d8bbc8b	// th.extu X25, X23, 31, 24
	WORD	$0x5d0c3d0b	// th.extu X26, X24, 23, 16
	WORD	$0x3c8abe0b	// th.extu X28, X21, 15, 8
	WORD	$0x1c0b3e8b	// th.extu X29, X22, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X19, X19
	XOR	X26, X19, X19
	XOR	X28, X19, X19
	XOR	X29, X19, X19
	WORD	$0x7d8c3c8b	// th.extu X25, X24, 31, 24
	WORD	$0x5d0abd0b	// th.extu X26, X21, 23, 16
	WORD	$0x3c8b3e0b	// th.extu X28, X22, 15, 8
	WORD	$0x1c0bbe8b	// th.extu X29, X23, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X20, X20
	XOR	X26, X20, X20
	XOR	X28, X20, X20
	XOR	X29, X20, X20
	ADD	$32, X30, X30
	ADD	$16, X30, X25
	BNE	X25, X11, enc_rounds
	MOVWU	0(X30), X21
	MOVWU	4(X30), X22
	MOVWU	8(X30), X23
	MOVWU	12(X30), X24
	WORD	$0x7d88bc8b	// th.extu X25, X17, 31, 24
	WORD	$0x5d093d0b	// th.extu X26, X18, 23, 16
	WORD	$0x3c89be0b	// th.extu X28, X19, 15, 8
	WORD	$0x1c0a3e8b	// th.extu X29, X20, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X21, X21
	XOR	X26, X21, X21
	XOR	X28, X21, X21
	XOR	X29, X21, X21
	WORD	$0x7d893c8b	// th.extu X25, X18, 31, 24
	WORD	$0x5d09bd0b	// th.extu X26, X19, 23, 16
	WORD	$0x3c8a3e0b	// th.extu X28, X20, 15, 8
	WORD	$0x1c08be8b	// th.extu X29, X17, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X22, X22
	XOR	X26, X22, X22
	XOR	X28, X22, X22
	XOR	X29, X22, X22
	WORD	$0x7d89bc8b	// th.extu X25, X19, 31, 24
	WORD	$0x5d0a3d0b	// th.extu X26, X20, 23, 16
	WORD	$0x3c88be0b	// th.extu X28, X17, 15, 8
	WORD	$0x1c093e8b	// th.extu X29, X18, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X23, X23
	XOR	X26, X23, X23
	XOR	X28, X23, X23
	XOR	X29, X23, X23
	WORD	$0x7d8a3c8b	// th.extu X25, X20, 31, 24
	WORD	$0x5d08bd0b	// th.extu X26, X17, 23, 16
	WORD	$0x3c893e0b	// th.extu X28, X18, 15, 8
	WORD	$0x1c09be8b	// th.extu X29, X19, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X24, X24
	XOR	X26, X24, X24
	XOR	X28, X24, X24
	XOR	X29, X24, X24
	MOVWU	0(X11), X17
	MOVWU	4(X11), X18
	MOVWU	8(X11), X19
	MOVWU	12(X11), X20
	WORD	$0x7d8abc8b	// th.extu X25, X21, 31, 24
	WORD	$0x5d0b3d0b	// th.extu X26, X22, 23, 16
	WORD	$0x3c8bbe0b	// th.extu X28, X23, 15, 8
	WORD	$0x1c0c3e8b	// th.extu X29, X24, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X17, X17
	XOR	X26, X17, X17
	XOR	X28, X17, X17
	XOR	X29, X17, X17
	WORD	$0x7d8b3c8b	// th.extu X25, X22, 31, 24
	WORD	$0x5d0bbd0b	// th.extu X26, X23, 23, 16
	WORD	$0x3c8c3e0b	// th.extu X28, X24, 15, 8
	WORD	$0x1c0abe8b	// th.extu X29, X21, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X18, X18
	XOR	X26, X18, X18
	XOR	X28, X18, X18
	XOR	X29, X18, X18
	WORD	$0x7d8bbc8b	// th.extu X25, X23, 31, 24
	WORD	$0x5d0c3d0b	// th.extu X26, X24, 23, 16
	WORD	$0x3c8abe0b	// th.extu X28, X21, 15, 8
	WORD	$0x1c0b3e8b	// th.extu X29, X22, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X19, X19
	XOR	X26, X19, X19
	XOR	X28, X19, X19
	XOR	X29, X19, X19
	WORD	$0x7d8c3c8b	// th.extu X25, X24, 31, 24
	WORD	$0x5d0abd0b	// th.extu X26, X21, 23, 16
	WORD	$0x3c8b3e0b	// th.extu X28, X22, 15, 8
	WORD	$0x1c0bbe8b	// th.extu X29, X23, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X20, X20
	XOR	X26, X20, X20
	XOR	X28, X20, X20
	XOR	X29, X20, X20
	WORD	$0x9008988b	// th.revw X17, X17
	MOVW	X17, 0(X5)
	WORD	$0x9009190b	// th.revw X18, X18
	MOVW	X18, 4(X5)
	WORD	$0x9009998b	// th.revw X19, X19
	MOVW	X19, 8(X5)
	WORD	$0x900a1a0b	// th.revw X20, X20
	MOVW	X20, 12(X5)
	RET

// func ctr32BlocksAsm(nr int, xk *uint32, dst, src *byte, n int, counter *byte)
//
// For n >= 1 blocks: dst = src ^ AES(counter), counter[12:16]++ (big-endian,
// wrapping at 2^32), per block. dst and src may be the same.
TEXT ·ctr32BlocksAsm(SB), NOSPLIT, $0-48
	MOV	nr+0(FP), X11
	MOV	xk+8(FP), X10
	MOV	dst+16(FP), X5
	MOV	src+24(FP), X6
	MOV	n+32(FP), X7
	MOV	counter+40(FP), X8
	SLL	$4, X11, X11
	ADD	X10, X11, X11
	MOV	$·te0(SB), X12
	MOV	$·te1(SB), X13
	MOV	$·te2(SB), X14
	MOV	$·te3(SB), X15
	MOV	$·sbox0(SB), X16
	MOVWU	12(X8), X9
	WORD	$0x9004948b	// th.revw X9, X9
ctr_block:
	MOVWU	0(X8), X17
	WORD	$0x9008988b	// th.revw X17, X17
	MOVWU	4(X8), X18
	WORD	$0x9009190b	// th.revw X18, X18
	MOVWU	8(X8), X19
	WORD	$0x9009998b	// th.revw X19, X19
	MOV	X9, X20
	MOVWU	0(X10), X21
	XOR	X21, X17, X17
	MOVWU	4(X10), X22
	XOR	X22, X18, X18
	MOVWU	8(X10), X23
	XOR	X23, X19, X19
	MOVWU	12(X10), X24
	XOR	X24, X20, X20
	ADD	$16, X10, X30
ctr_rounds:
	MOVWU	0(X30), X21
	MOVWU	4(X30), X22
	MOVWU	8(X30), X23
	MOVWU	12(X30), X24
	WORD	$0x7d88bc8b	// th.extu X25, X17, 31, 24
	WORD	$0x5d093d0b	// th.extu X26, X18, 23, 16
	WORD	$0x3c89be0b	// th.extu X28, X19, 15, 8
	WORD	$0x1c0a3e8b	// th.extu X29, X20, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X21, X21
	XOR	X26, X21, X21
	XOR	X28, X21, X21
	XOR	X29, X21, X21
	WORD	$0x7d893c8b	// th.extu X25, X18, 31, 24
	WORD	$0x5d09bd0b	// th.extu X26, X19, 23, 16
	WORD	$0x3c8a3e0b	// th.extu X28, X20, 15, 8
	WORD	$0x1c08be8b	// th.extu X29, X17, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X22, X22
	XOR	X26, X22, X22
	XOR	X28, X22, X22
	XOR	X29, X22, X22
	WORD	$0x7d89bc8b	// th.extu X25, X19, 31, 24
	WORD	$0x5d0a3d0b	// th.extu X26, X20, 23, 16
	WORD	$0x3c88be0b	// th.extu X28, X17, 15, 8
	WORD	$0x1c093e8b	// th.extu X29, X18, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X23, X23
	XOR	X26, X23, X23
	XOR	X28, X23, X23
	XOR	X29, X23, X23
	WORD	$0x7d8a3c8b	// th.extu X25, X20, 31, 24
	WORD	$0x5d08bd0b	// th.extu X26, X17, 23, 16
	WORD	$0x3c893e0b	// th.extu X28, X18, 15, 8
	WORD	$0x1c09be8b	// th.extu X29, X19, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X24, X24
	XOR	X26, X24, X24
	XOR	X28, X24, X24
	XOR	X29, X24, X24
	MOVWU	16(X30), X17
	MOVWU	20(X30), X18
	MOVWU	24(X30), X19
	MOVWU	28(X30), X20
	WORD	$0x7d8abc8b	// th.extu X25, X21, 31, 24
	WORD	$0x5d0b3d0b	// th.extu X26, X22, 23, 16
	WORD	$0x3c8bbe0b	// th.extu X28, X23, 15, 8
	WORD	$0x1c0c3e8b	// th.extu X29, X24, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X17, X17
	XOR	X26, X17, X17
	XOR	X28, X17, X17
	XOR	X29, X17, X17
	WORD	$0x7d8b3c8b	// th.extu X25, X22, 31, 24
	WORD	$0x5d0bbd0b	// th.extu X26, X23, 23, 16
	WORD	$0x3c8c3e0b	// th.extu X28, X24, 15, 8
	WORD	$0x1c0abe8b	// th.extu X29, X21, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X18, X18
	XOR	X26, X18, X18
	XOR	X28, X18, X18
	XOR	X29, X18, X18
	WORD	$0x7d8bbc8b	// th.extu X25, X23, 31, 24
	WORD	$0x5d0c3d0b	// th.extu X26, X24, 23, 16
	WORD	$0x3c8abe0b	// th.extu X28, X21, 15, 8
	WORD	$0x1c0b3e8b	// th.extu X29, X22, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X19, X19
	XOR	X26, X19, X19
	XOR	X28, X19, X19
	XOR	X29, X19, X19
	WORD	$0x7d8c3c8b	// th.extu X25, X24, 31, 24
	WORD	$0x5d0abd0b	// th.extu X26, X21, 23, 16
	WORD	$0x3c8b3e0b	// th.extu X28, X22, 15, 8
	WORD	$0x1c0bbe8b	// th.extu X29, X23, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X20, X20
	XOR	X26, X20, X20
	XOR	X28, X20, X20
	XOR	X29, X20, X20
	ADD	$32, X30, X30
	ADD	$16, X30, X25
	BNE	X25, X11, ctr_rounds
	MOVWU	0(X30), X21
	MOVWU	4(X30), X22
	MOVWU	8(X30), X23
	MOVWU	12(X30), X24
	WORD	$0x7d88bc8b	// th.extu X25, X17, 31, 24
	WORD	$0x5d093d0b	// th.extu X26, X18, 23, 16
	WORD	$0x3c89be0b	// th.extu X28, X19, 15, 8
	WORD	$0x1c0a3e8b	// th.extu X29, X20, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X21, X21
	XOR	X26, X21, X21
	XOR	X28, X21, X21
	XOR	X29, X21, X21
	WORD	$0x7d893c8b	// th.extu X25, X18, 31, 24
	WORD	$0x5d09bd0b	// th.extu X26, X19, 23, 16
	WORD	$0x3c8a3e0b	// th.extu X28, X20, 15, 8
	WORD	$0x1c08be8b	// th.extu X29, X17, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X22, X22
	XOR	X26, X22, X22
	XOR	X28, X22, X22
	XOR	X29, X22, X22
	WORD	$0x7d89bc8b	// th.extu X25, X19, 31, 24
	WORD	$0x5d0a3d0b	// th.extu X26, X20, 23, 16
	WORD	$0x3c88be0b	// th.extu X28, X17, 15, 8
	WORD	$0x1c093e8b	// th.extu X29, X18, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X23, X23
	XOR	X26, X23, X23
	XOR	X28, X23, X23
	XOR	X29, X23, X23
	WORD	$0x7d8a3c8b	// th.extu X25, X20, 31, 24
	WORD	$0x5d08bd0b	// th.extu X26, X17, 23, 16
	WORD	$0x3c893e0b	// th.extu X28, X18, 15, 8
	WORD	$0x1c09be8b	// th.extu X29, X19, 7, 0
	WORD	$0xc5964c8b	// th.lrwu X25, X12, X25, 2
	WORD	$0xc5a6cd0b	// th.lrwu X26, X13, X26, 2
	WORD	$0xc5c74e0b	// th.lrwu X28, X14, X28, 2
	WORD	$0xc5d7ce8b	// th.lrwu X29, X15, X29, 2
	XOR	X25, X24, X24
	XOR	X26, X24, X24
	XOR	X28, X24, X24
	XOR	X29, X24, X24
	MOVWU	0(X11), X17
	MOVWU	4(X11), X18
	MOVWU	8(X11), X19
	MOVWU	12(X11), X20
	WORD	$0x7d8abc8b	// th.extu X25, X21, 31, 24
	WORD	$0x5d0b3d0b	// th.extu X26, X22, 23, 16
	WORD	$0x3c8bbe0b	// th.extu X28, X23, 15, 8
	WORD	$0x1c0c3e8b	// th.extu X29, X24, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X17, X17
	XOR	X26, X17, X17
	XOR	X28, X17, X17
	XOR	X29, X17, X17
	WORD	$0x7d8b3c8b	// th.extu X25, X22, 31, 24
	WORD	$0x5d0bbd0b	// th.extu X26, X23, 23, 16
	WORD	$0x3c8c3e0b	// th.extu X28, X24, 15, 8
	WORD	$0x1c0abe8b	// th.extu X29, X21, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X18, X18
	XOR	X26, X18, X18
	XOR	X28, X18, X18
	XOR	X29, X18, X18
	WORD	$0x7d8bbc8b	// th.extu X25, X23, 31, 24
	WORD	$0x5d0c3d0b	// th.extu X26, X24, 23, 16
	WORD	$0x3c8abe0b	// th.extu X28, X21, 15, 8
	WORD	$0x1c0b3e8b	// th.extu X29, X22, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X19, X19
	XOR	X26, X19, X19
	XOR	X28, X19, X19
	XOR	X29, X19, X19
	WORD	$0x7d8c3c8b	// th.extu X25, X24, 31, 24
	WORD	$0x5d0abd0b	// th.extu X26, X21, 23, 16
	WORD	$0x3c8b3e0b	// th.extu X28, X22, 15, 8
	WORD	$0x1c0bbe8b	// th.extu X29, X23, 7, 0
	WORD	$0x81984c8b	// th.lrbu X25, X16, X25, 0
	WORD	$0x81a84d0b	// th.lrbu X26, X16, X26, 0
	WORD	$0x81c84e0b	// th.lrbu X28, X16, X28, 0
	WORD	$0x81d84e8b	// th.lrbu X29, X16, X29, 0
	SLL	$24, X25, X25
	SLL	$16, X26, X26
	SLL	$8, X28, X28
	XOR	X25, X20, X20
	XOR	X26, X20, X20
	XOR	X28, X20, X20
	XOR	X29, X20, X20
	WORD	$0x9008988b	// th.revw X17, X17
	MOVWU	0(X6), X21
	WORD	$0x9009190b	// th.revw X18, X18
	MOVWU	4(X6), X22
	WORD	$0x9009998b	// th.revw X19, X19
	MOVWU	8(X6), X23
	WORD	$0x900a1a0b	// th.revw X20, X20
	MOVWU	12(X6), X24
	XOR	X17, X21, X21
	MOVW	X21, 0(X5)
	XOR	X18, X22, X22
	MOVW	X22, 4(X5)
	XOR	X19, X23, X23
	MOVW	X23, 8(X5)
	XOR	X20, X24, X24
	MOVW	X24, 12(X5)
	ADDW	$1, X9, X9
	ADD	$16, X5, X5
	ADD	$16, X6, X6
	SUB	$1, X7, X7
	BNE	X7, ZERO, ctr_block
	WORD	$0x9004948b	// th.revw X9, X9
	MOVW	X9, 12(X8)
	RET
